# Use an official Node runtime as a base image
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire application to the working directory
COPY . .

# Build the app
RUN npm run build

# Expose the port that your app will run on
EXPOSE 4173

# Define the command to run your app
CMD ["npm", "run", "preview"]
